[2023-08-09T04:09:42.912+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: local_gcd_etl_basic.download_file_using_BashOperator manual__2023-08-09T04:09:41.774489+00:00 [queued]>
[2023-08-09T04:09:42.923+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: local_gcd_etl_basic.download_file_using_BashOperator manual__2023-08-09T04:09:41.774489+00:00 [queued]>
[2023-08-09T04:09:42.923+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-09T04:09:42.940+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): download_file_using_BashOperator> on 2023-08-09 04:09:41.774489+00:00
[2023-08-09T04:09:42.946+0000] {standard_task_runner.py:57} INFO - Started process 692 to run task
[2023-08-09T04:09:42.948+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'local_gcd_etl_basic', 'download_file_using_BashOperator', 'manual__2023-08-09T04:09:41.774489+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/example_gcs_upload_download.py', '--cfg-path', '/tmp/tmpac760iob']
[2023-08-09T04:09:42.950+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask download_file_using_BashOperator
[2023-08-09T04:09:42.981+0000] {task_command.py:410} INFO - Running <TaskInstance: local_gcd_etl_basic.download_file_using_BashOperator manual__2023-08-09T04:09:41.774489+00:00 [running]> on host 738c524d2ce7
[2023-08-09T04:09:43.038+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='local_gcd_etl_basic' AIRFLOW_CTX_TASK_ID='download_file_using_BashOperator' AIRFLOW_CTX_EXECUTION_DATE='2023-08-09T04:09:41.774489+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-09T04:09:41.774489+00:00'
[2023-08-09T04:09:43.040+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-09T04:09:43.040+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl "https://api.mockaroo.com/api/6872a950?count=1000&key=5f671810" > resources/resmock_users.csv']
[2023-08-09T04:09:43.053+0000] {subprocess.py:86} INFO - Output:
[2023-08-09T04:09:43.055+0000] {subprocess.py:93} INFO - /bin/bash: line 1: resources/resmock_users.csv: No such file or directory
[2023-08-09T04:09:43.056+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-09T04:09:43.064+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-09T04:09:43.067+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=local_gcd_etl_basic, task_id=download_file_using_BashOperator, execution_date=20230809T040941, start_date=20230809T040942, end_date=20230809T040943
[2023-08-09T04:09:43.075+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 54 for task download_file_using_BashOperator (Bash command failed. The command returned a non-zero exit code 1.; 692)
[2023-08-09T04:09:43.120+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-09T04:09:43.157+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
